<?php

$colorKeys = ['primary', 'accent', 'background', 'surface', 'text', 'text_muted'];

return [
    'templates' => [
        'lumiere' => [
            'label' => 'Lumiere',
            'description' => 'Gastronomía de autor: carbón cálido, oro y tarjetas premium.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/lumiere.svg',
        ],
        'nocturne' => [
            'label' => 'Nocturno',
            'description' => 'Modo oscuro, plato destacado con overlay y categorías fijas.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/nocturne.svg',
        ],
        'temporada' => [
            'label' => 'Temporada',
            'description' => 'Menú claro, tarjetas con foto y etiquetas de alérgenos.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/temporada.svg',
        ],
        'catalogo' => [
            'label' => 'Catálogo',
            'description' => 'Listado horizontal compacto con chips de categoría fijos.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/catalogo.svg',
        ],
        'otaku' => [
            'label' => 'Otaku',
            'description' => 'Naranja neón sobre negro. Estilo japonés pop, ideal para ramen y street food.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/otaku.svg',
        ],
        'japo' => [
            'label' => 'Japo',
            'description' => 'Rojo lacado, negro y oro. Elegancia japonesa tradicional.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/japo.svg',
        ],
        'fastfood' => [
            'label' => 'Fastfood',
            'description' => 'Rojo y amarillo, tipografía bold y cards horizontales.',
            'group' => 'specialty',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/fastfood.svg',
        ],
        'pizza' => [
            'label' => 'Pizza',
            'description' => 'Tomate, mozzarella y albahaca. Ideal para pizzerías y delivery.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/pizza.svg',
        ],
        'mar' => [
            'label' => 'Azure Waves',
            'description' => 'Costa mediterránea: azul profundo, emblema circular y tarjetas horizontales.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/mar.svg',
        ],
        'elegance' => [
            'label' => 'Elegance',
            'description' => 'Fine dining: serif, espacio generoso y acentos dorados.',
            'group' => 'specialty',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/elegance.svg',
        ],
        'asador' => [
            'label' => 'Asador',
            'description' => 'Brasa y carbón: oscuro, brasas y naranja fuego.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/asador.svg',
        ],
        'pasion' => [
            'label' => 'Pasión',
            'description' => 'Carta clara y tradicional, ideal como plantilla de entrada.',
            'group' => 'classic',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/pasion.svg',
        ],
        'saffron' => [
            'label' => 'Azafrán',
            'description' => 'Mediterráneo cálido: terracota, salvia y tipografía editorial.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/saffron.svg',
        ],
        'velvet' => [
            'label' => 'Velvet Bloom',
            'description' => 'Artesanal claro: crema, salvia y plato destacado con tarjetas horizontales.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/velvet.svg',
        ],
        'maison' => [
            'label' => 'Maison',
            'description' => 'Alta gama: hero tipográfico, platos estrella en overlay y carta editorial.',
            'group' => 'modern',
            'recommended' => true,
            'preview_slug' => 'demo-maison',
            'preview_image' => 'img/admin/templates/maison.svg',
        ],
    ],

    'hero_presets' => [
        'dark_bleed' => [
            'preset' => 'dark_bleed',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'rounded',
        ],
        'compact_card' => [
            'preset' => 'compact_card',
            'ratio' => '4:3',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'rounded',
        ],
        'circle_emblem' => [
            'preset' => 'circle_emblem',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'circle',
        ],
        'spotlight_dish' => [
            'preset' => 'spotlight_dish',
            'ratio' => '16:9',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
            'fallback' => 'compact_card',
        ],
        'typographic_dark' => [
            'preset' => 'typographic_dark',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
        ],
        'minimal_bar' => [
            'preset' => 'minimal_bar',
            'ratio' => '16:9',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
        ],
    ],

    'template_hero' => [
        'lumiere' => 'dark_bleed',
        'otaku' => 'dark_bleed',
        'japo' => 'dark_bleed',
        'fastfood' => 'dark_bleed',
        'asador' => 'dark_bleed',
        'pasion' => 'compact_card',
        'temporada' => 'compact_card',
        'pizza' => 'compact_card',
        'mar' => 'circle_emblem',
        'elegance' => 'circle_emblem',
        'nocturne' => 'typographic_dark',
        'catalogo' => 'minimal_bar',
        'saffron' => 'circle_emblem',
        'velvet' => 'spotlight_dish',
        'maison' => 'typographic_dark',
    ],

    'color_keys' => [
        'primary' => 'Color principal',
        'accent' => 'Color de acento',
        'background' => 'Fondo',
        'surface' => 'Tarjetas / superficies',
        'text' => 'Texto',
        'text_muted' => 'Texto secundario',
    ],

    'font_keys' => [
        'font_heading' => 'Fuente de títulos',
        'font_body' => 'Fuente de textos',
    ],

    'font_defaults' => [
        'font_heading' => 'playfair',
        'font_body' => 'inter',
    ],

    'fonts' => [
        'inter' => ['label' => 'Inter', 'family' => 'Inter', 'category' => 'sans-serif', 'weights' => '400;500;600;700'],
        'open_sans' => ['label' => 'Open Sans', 'family' => 'Open Sans', 'category' => 'sans-serif', 'weights' => '400;600;700'],
        'montserrat' => ['label' => 'Montserrat', 'family' => 'Montserrat', 'category' => 'sans-serif', 'weights' => '500;600;700'],
        'poppins' => ['label' => 'Poppins', 'family' => 'Poppins', 'category' => 'sans-serif', 'weights' => '400;500;600'],
        'lora' => ['label' => 'Lora', 'family' => 'Lora', 'category' => 'serif', 'weights' => '400;600;700'],
        'playfair' => ['label' => 'Playfair Display', 'family' => 'Playfair Display', 'category' => 'serif', 'weights' => '400;600;700'],
        'cormorant' => ['label' => 'Cormorant Garamond', 'family' => 'Cormorant Garamond', 'category' => 'serif', 'weights' => '400;600;700'],
        'merriweather' => ['label' => 'Merriweather', 'family' => 'Merriweather', 'category' => 'serif', 'weights' => '400;700'],
        'bebas_neue' => ['label' => 'Bebas Neue', 'family' => 'Bebas Neue', 'category' => 'sans-serif', 'weights' => '400'],
        'noto_sans_jp' => ['label' => 'Noto Sans JP', 'family' => 'Noto Sans JP', 'category' => 'sans-serif', 'weights' => '400;500;700;900'],
    ],

    'defaults' => [
        'pasion' => [
            'primary' => '#8b0000',
            'accent' => '#d4a017',
            'background' => '#fff8f0',
            'surface' => '#ffffff',
            'text' => '#2c1810',
            'text_muted' => '#6b5344',
        ],
        'lumiere' => [
            'primary' => '#f2ca50',
            'accent' => '#d4af37',
            'background' => '#16130b',
            'surface' => '#1f1b13',
            'text' => '#eae1d4',
            'text_muted' => '#d0c5af',
            'font_heading' => 'playfair',
            'font_body' => 'inter',
        ],
        'nocturne' => [
            'primary' => '#f0e6d0',
            'accent' => '#d4af37',
            'background' => '#0f1218',
            'surface' => '#181e28',
            'text' => '#f5f3ee',
            'text_muted' => '#aeb8c4',
        ],
        'temporada' => [
            'primary' => '#1e3a5f',
            'accent' => '#2563eb',
            'background' => '#f4f6f9',
            'surface' => '#ffffff',
            'text' => '#0f172a',
            'text_muted' => '#64748b',
        ],
        'catalogo' => [
            'primary' => '#334155',
            'accent' => '#0ea5e9',
            'background' => '#f8fafc',
            'surface' => '#ffffff',
            'text' => '#1e293b',
            'text_muted' => '#64748b',
        ],
        'otaku' => [
            'primary' => '#ff5500',
            'accent' => '#ffb800',
            'background' => '#0a0a0a',
            'surface' => '#141414',
            'text' => '#ffffff',
            'text_muted' => '#ff9944',
            'font_heading' => 'bebas_neue',
            'font_body' => 'noto_sans_jp',
        ],
        'japo' => [
            'primary' => '#c41e3a',
            'accent' => '#d4af37',
            'background' => '#0f0808',
            'surface' => '#1a1010',
            'text' => '#f5f0eb',
            'text_muted' => '#c4a882',
            'font_heading' => 'noto_sans_jp',
            'font_body' => 'inter',
        ],
        'fastfood' => [
            'primary' => '#d62828',
            'accent' => '#ffbe0b',
            'background' => '#fff5e6',
            'surface' => '#ffffff',
            'text' => '#141414',
            'text_muted' => '#5c4033',
            'font_heading' => 'bebas_neue',
            'font_body' => 'open_sans',
        ],
        'pizza' => [
            'primary' => '#c62828',
            'accent' => '#2e7d32',
            'background' => '#fff8f0',
            'surface' => '#ffffff',
            'text' => '#1b1b1b',
            'text_muted' => '#6d4c41',
            'font_heading' => 'bebas_neue',
            'font_body' => 'open_sans',
        ],
        'mar' => [
            'primary' => '#002046',
            'accent' => '#306670',
            'background' => '#f9f9f9',
            'surface' => '#ffffff',
            'text' => '#1a1c1c',
            'text_muted' => '#44474e',
            'font_heading' => 'playfair',
            'font_body' => 'inter',
        ],
        'elegance' => [
            'primary' => '#1a1a2e',
            'accent' => '#c9a962',
            'background' => '#faf8f5',
            'surface' => '#ffffff',
            'text' => '#1a1a2e',
            'text_muted' => '#6b6b7b',
            'font_heading' => 'playfair',
            'font_body' => 'lora',
        ],
        'asador' => [
            'primary' => '#ff5722',
            'accent' => '#ffab40',
            'background' => '#141010',
            'surface' => '#1e1816',
            'text' => '#f5f0eb',
            'text_muted' => '#bcaaa4',
            'font_heading' => 'montserrat',
            'font_body' => 'inter',
        ],
        'saffron' => [
            'primary' => '#c75b3a',
            'accent' => '#6b8f71',
            'background' => '#faf6f1',
            'surface' => '#ffffff',
            'text' => '#2c1810',
            'text_muted' => '#7a6558',
            'font_heading' => 'cormorant',
            'font_body' => 'montserrat',
        ],
        'velvet' => [
            'primary' => '#4f6353',
            'accent' => '#8da290',
            'background' => '#fdf9f0',
            'surface' => '#ffffff',
            'text' => '#1c1c16',
            'text_muted' => '#5f5e5e',
            'font_heading' => 'playfair',
            'font_body' => 'montserrat',
        ],
        'maison' => [
            'primary' => '#f5f3ef',
            'accent' => '#c4a574',
            'background' => '#0f0e0d',
            'surface' => '#1a1917',
            'text' => '#f5f3ef',
            'text_muted' => '#8a8478',
            'font_heading' => 'cormorant',
            'font_body' => 'lora',
        ],
    ],

  /*
  | Paletas rápidas por plantilla (nombre => colores)
  */
    'presets' => [
        'lumiere' => [
            'Carbón y oro' => [
                'primary' => '#f2ca50',
                'accent' => '#d4af37',
                'background' => '#16130b',
                'surface' => '#1f1b13',
                'text' => '#eae1d4',
                'text_muted' => '#d0c5af',
            ],
            'Noche elegante' => [
                'primary' => '#e9c349',
                'accent' => '#ffe088',
                'background' => '#110e07',
                'surface' => '#231f17',
                'text' => '#f5f0e8',
                'text_muted' => '#b8a88a',
            ],
            'Medianoche azul' => [
                'primary' => '#f2ca50',
                'accent' => '#bfcdff',
                'background' => '#0f1218',
                'surface' => '#1a1f28',
                'text' => '#eceff1',
                'text_muted' => '#9aa8b8',
            ],
        ],
        'pasion' => [
            'Vino tinto' => [
                'primary' => '#8b0000',
                'accent' => '#d4a017',
                'background' => '#fff8f0',
                'surface' => '#ffffff',
                'text' => '#2c1810',
                'text_muted' => '#6b5344',
            ],
        ],
        'nocturne' => [
            'Coctelería' => [
                'primary' => '#7ec8ff',
                'accent' => '#c9a962',
                'background' => '#0a0e14',
                'surface' => '#141a22',
                'text' => '#f4f7fb',
                'text_muted' => '#9aa8b8',
            ],
        ],
        'temporada' => [
            'Primavera' => [
                'primary' => '#1e3a5f',
                'accent' => '#2563eb',
                'background' => '#f4f6f9',
                'surface' => '#ffffff',
                'text' => '#0f172a',
                'text_muted' => '#64748b',
            ],
        ],
        'catalogo' => [
            'Minimal' => [
                'primary' => '#334155',
                'accent' => '#0ea5e9',
                'background' => '#f8fafc',
                'surface' => '#ffffff',
                'text' => '#1e293b',
                'text_muted' => '#64748b',
            ],
        ],
        'otaku' => [
            'Neón naranja' => [
                'primary' => '#ff5500',
                'accent' => '#ffb800',
                'background' => '#0a0a0a',
                'surface' => '#141414',
                'text' => '#ffffff',
                'text_muted' => '#ff9944',
            ],
        ],
        'japo' => [
            'Lacado imperial' => [
                'primary' => '#c41e3a',
                'accent' => '#d4af37',
                'background' => '#0f0808',
                'surface' => '#1a1010',
                'text' => '#f5f0eb',
                'text_muted' => '#c4a882',
            ],
        ],
        'fastfood' => [
            'Burger clásico' => [
                'primary' => '#e53935',
                'accent' => '#ffc107',
                'background' => '#fff8e7',
                'surface' => '#ffffff',
                'text' => '#1a1a1a',
                'text_muted' => '#5d4037',
            ],
        ],
        'pizza' => [
            'Forno clásico' => [
                'primary' => '#c62828',
                'accent' => '#2e7d32',
                'background' => '#fff8f0',
                'surface' => '#ffffff',
                'text' => '#1b1b1b',
                'text_muted' => '#6d4c41',
            ],
        ],
        'mar' => [
            'Azure Waves' => [
                'primary' => '#002046',
                'accent' => '#306670',
                'background' => '#f9f9f9',
                'surface' => '#ffffff',
                'text' => '#1a1c1c',
                'text_muted' => '#44474e',
            ],
            'Mediterráneo clásico' => [
                'primary' => '#0277bd',
                'accent' => '#00b4d8',
                'background' => '#e0f7fa',
                'surface' => '#ffffff',
                'text' => '#0d3b5c',
                'text_muted' => '#546e7a',
            ],
        ],
        'elegance' => [
            'Ivory & gold' => [
                'primary' => '#1a1a2e',
                'accent' => '#c9a962',
                'background' => '#faf8f5',
                'surface' => '#ffffff',
                'text' => '#1a1a2e',
                'text_muted' => '#6b6b7b',
            ],
        ],
        'asador' => [
            'Brasa viva' => [
                'primary' => '#ff5722',
                'accent' => '#ffab40',
                'background' => '#141010',
                'surface' => '#1e1816',
                'text' => '#f5f0eb',
                'text_muted' => '#bcaaa4',
            ],
        ],
        'saffron' => [
            'Terracota mediterránea' => [
                'primary' => '#c75b3a',
                'accent' => '#6b8f71',
                'background' => '#faf6f1',
                'surface' => '#ffffff',
                'text' => '#2c1810',
                'text_muted' => '#7a6558',
            ],
            'Atardecer costero' => [
                'primary' => '#d4764a',
                'accent' => '#4a7c59',
                'background' => '#fff9f4',
                'surface' => '#ffffff',
                'text' => '#3d2817',
                'text_muted' => '#8b7355',
            ],
        ],
        'velvet' => [
            'Salvia artesanal' => [
                'primary' => '#4f6353',
                'accent' => '#8da290',
                'background' => '#fdf9f0',
                'surface' => '#ffffff',
                'text' => '#1c1c16',
                'text_muted' => '#5f5e5e',
            ],
            'Crema botánica' => [
                'primary' => '#5a6b52',
                'accent' => '#a8b5a0',
                'background' => '#faf7ef',
                'surface' => '#ffffff',
                'text' => '#242420',
                'text_muted' => '#6b6a65',
            ],
        ],
        'maison' => [
            'Espresso y oro' => [
                'primary' => '#f5f3ef',
                'accent' => '#c4a574',
                'background' => '#0f0e0d',
                'surface' => '#1a1917',
                'text' => '#f5f3ef',
                'text_muted' => '#8a8478',
            ],
            'Noche de perla' => [
                'primary' => '#faf9f7',
                'accent' => '#d4b896',
                'background' => '#0a0908',
                'surface' => '#141210',
                'text' => '#faf9f7',
                'text_muted' => '#9a9488',
            ],
        ],
    ],
];
