<?php

$colorKeys = ['primary', 'accent', 'background', 'surface', 'text', 'text_muted'];

return [
    'templates' => [
        'lumiere' => [
            'label' => "L'Essence",
            'description' => 'Modo oscuro, fotos grandes y tipografía elegante.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/lumiere.svg',
        ],
        'bistro' => [
            'label' => 'Bistro',
            'description' => 'Fondo claro, tarjetas y chips de categoría.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/bistro.svg',
        ],
        'nocturne' => [
            'label' => 'Nocturno',
            'description' => 'Modo oscuro, plato destacado con overlay y categorías fijas.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/nocturne.svg',
        ],
        'temporada' => [
            'label' => 'Temporada',
            'description' => 'Menú claro, tarjetas con foto y etiquetas de alérgenos.',
            'group' => 'modern',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/temporada.svg',
        ],
        'catalogo' => [
            'label' => 'Catálogo',
            'description' => 'Listado horizontal compacto con chips de categoría fijos.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/catalogo.svg',
        ],
        'otaku' => [
            'label' => 'Otaku',
            'description' => 'Naranja neón sobre negro. Estilo japonés pop, ideal para ramen y street food.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/otaku.svg',
        ],
        'japo' => [
            'label' => 'Japo',
            'description' => 'Rojo lacado, negro y oro. Elegancia japonesa tradicional.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/japo.svg',
        ],
        'fastfood' => [
            'label' => 'Fastfood',
            'description' => 'Rojo y amarillo, tipografía bold y cards horizontales.',
            'group' => 'specialty',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/fastfood.svg',
        ],
        'pizza' => [
            'label' => 'Pizza',
            'description' => 'Tomate, mozzarella y albahaca. Ideal para pizzerías y delivery.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/pizza.svg',
        ],
        'mar' => [
            'label' => 'Mar',
            'description' => 'Azules oceánicos para pescaderías, chiringuitos y marisquerías.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/mar.svg',
        ],
        'elegance' => [
            'label' => 'Elegance',
            'description' => 'Fine dining: serif, espacio generoso y acentos dorados.',
            'group' => 'specialty',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/elegance.svg',
        ],
        'asador' => [
            'label' => 'Asador',
            'description' => 'Brasa y carbón: oscuro, brasas y naranja fuego.',
            'group' => 'specialty',
            'recommended' => true,
            'preview_image' => 'img/admin/templates/asador.svg',
        ],
        'basic' => [
            'label' => 'Básica',
            'description' => 'Carta clara y compacta, ideal para cualquier negocio.',
            'group' => 'classic',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/basic.svg',
        ],
        'pasion' => [
            'label' => 'Pasión',
            'description' => 'Estilo cálido y tradicional.',
            'group' => 'classic',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/pasion.svg',
        ],
        'oriental' => [
            'label' => 'Oriental',
            'description' => 'Inspiración asiática.',
            'group' => 'classic',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/oriental.svg',
        ],
        'visual' => [
            'label' => 'Visual',
            'description' => 'Fotos grandes y menú horizontal.',
            'group' => 'classic',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/visual.svg',
        ],
        'saffron' => [
            'label' => 'Azafrán',
            'description' => 'Mediterráneo cálido: terracota, salvia y tipografía editorial.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/saffron.svg',
        ],
        'velvet' => [
            'label' => 'Terciopelo',
            'description' => 'Lounge oscuro: burdeos, cobre y hero tipográfico cinematográfico.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/velvet.svg',
        ],
        'atelier' => [
            'label' => 'Atelier',
            'description' => 'Carta cinematográfica: platos a pantalla completa y tipografía bold.',
            'group' => 'modern',
            'recommended' => false,
            'preview_image' => 'img/admin/templates/atelier.svg',
        ],
        'maison' => [
            'label' => 'Maison',
            'description' => 'Alta gama: hero tipográfico, platos estrella en overlay y carta editorial.',
            'group' => 'modern',
            'recommended' => true,
            'preview_slug' => 'demo-maison',
            'preview_image' => 'img/admin/templates/maison.svg',
        ],
    ],

    'hero_presets' => [
        'dark_bleed' => [
            'preset' => 'dark_bleed',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'rounded',
        ],
        'compact_card' => [
            'preset' => 'compact_card',
            'ratio' => '4:3',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'rounded',
        ],
        'circle_emblem' => [
            'preset' => 'circle_emblem',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => true,
            'logo_shape' => 'circle',
        ],
        'spotlight_dish' => [
            'preset' => 'spotlight_dish',
            'ratio' => '16:9',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
            'fallback' => 'compact_card',
        ],
        'typographic_dark' => [
            'preset' => 'typographic_dark',
            'ratio' => '16:9',
            'bleed' => true,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
        ],
        'minimal_bar' => [
            'preset' => 'minimal_bar',
            'ratio' => '16:9',
            'bleed' => false,
            'show_logo' => true,
            'show_chef' => false,
            'logo_shape' => 'rounded',
        ],
    ],

    'template_hero' => [
        'lumiere' => 'dark_bleed',
        'otaku' => 'dark_bleed',
        'japo' => 'dark_bleed',
        'fastfood' => 'dark_bleed',
        'asador' => 'dark_bleed',
        'oriental' => 'dark_bleed',
        'basic' => 'compact_card',
        'pasion' => 'compact_card',
        'temporada' => 'compact_card',
        'pizza' => 'compact_card',
        'mar' => 'compact_card',
        'visual' => 'compact_card',
        'elegance' => 'circle_emblem',
        'bistro' => 'spotlight_dish',
        'nocturne' => 'typographic_dark',
        'catalogo' => 'minimal_bar',
        'saffron' => 'circle_emblem',
        'velvet' => 'dark_bleed',
        'atelier' => 'typographic_dark',
        'maison' => 'typographic_dark',
    ],

    'color_keys' => [
        'primary' => 'Color principal',
        'accent' => 'Color de acento',
        'background' => 'Fondo',
        'surface' => 'Tarjetas / superficies',
        'text' => 'Texto',
        'text_muted' => 'Texto secundario',
    ],

    'font_keys' => [
        'font_heading' => 'Fuente de títulos',
        'font_body' => 'Fuente de textos',
    ],

    'font_defaults' => [
        'font_heading' => 'playfair',
        'font_body' => 'inter',
    ],

    'fonts' => [
        'inter' => ['label' => 'Inter', 'family' => 'Inter', 'category' => 'sans-serif', 'weights' => '400;500;600;700'],
        'open_sans' => ['label' => 'Open Sans', 'family' => 'Open Sans', 'category' => 'sans-serif', 'weights' => '400;600;700'],
        'montserrat' => ['label' => 'Montserrat', 'family' => 'Montserrat', 'category' => 'sans-serif', 'weights' => '500;600;700'],
        'poppins' => ['label' => 'Poppins', 'family' => 'Poppins', 'category' => 'sans-serif', 'weights' => '400;500;600'],
        'lora' => ['label' => 'Lora', 'family' => 'Lora', 'category' => 'serif', 'weights' => '400;600;700'],
        'playfair' => ['label' => 'Playfair Display', 'family' => 'Playfair Display', 'category' => 'serif', 'weights' => '400;600;700'],
        'cormorant' => ['label' => 'Cormorant Garamond', 'family' => 'Cormorant Garamond', 'category' => 'serif', 'weights' => '400;600;700'],
        'merriweather' => ['label' => 'Merriweather', 'family' => 'Merriweather', 'category' => 'serif', 'weights' => '400;700'],
        'bebas_neue' => ['label' => 'Bebas Neue', 'family' => 'Bebas Neue', 'category' => 'sans-serif', 'weights' => '400'],
        'noto_sans_jp' => ['label' => 'Noto Sans JP', 'family' => 'Noto Sans JP', 'category' => 'sans-serif', 'weights' => '400;500;700;900'],
    ],

    'defaults' => [
        'basic' => [
            'primary' => '#0074d9',
            'accent' => '#e65100',
            'background' => '#ffffff',
            'surface' => '#f8f9fa',
            'text' => '#212529',
            'text_muted' => '#6c757d',
        ],
        'pasion' => [
            'primary' => '#8b0000',
            'accent' => '#d4a017',
            'background' => '#fff8f0',
            'surface' => '#ffffff',
            'text' => '#2c1810',
            'text_muted' => '#6b5344',
        ],
        'oriental' => [
            'primary' => '#c41e3a',
            'accent' => '#d4af37',
            'background' => '#1a1a1a',
            'surface' => '#2d2d2d',
            'text' => '#f5f5f5',
            'text_muted' => '#a0a0a0',
        ],
        'visual' => [
            'primary' => '#1565c0',
            'accent' => '#ff6f00',
            'background' => '#fafafa',
            'surface' => '#ffffff',
            'text' => '#212121',
            'text_muted' => '#757575',
        ],
        'lumiere' => [
            'primary' => '#c9a962',
            'accent' => '#e8d5a3',
            'background' => '#080b0f',
            'surface' => '#121820',
            'text' => '#faf8f5',
            'text_muted' => '#9ba3ae',
            'font_heading' => 'playfair',
            'font_body' => 'inter',
        ],
        'bistro' => [
            'primary' => '#1a365d',
            'accent' => '#e8b923',
            'background' => '#eef1f6',
            'surface' => '#ffffff',
            'text' => '#0f172a',
            'text_muted' => '#64748b',
        ],
        'nocturne' => [
            'primary' => '#f0e6d0',
            'accent' => '#d4af37',
            'background' => '#0f1218',
            'surface' => '#181e28',
            'text' => '#f5f3ee',
            'text_muted' => '#aeb8c4',
        ],
        'temporada' => [
            'primary' => '#1e3a5f',
            'accent' => '#2563eb',
            'background' => '#f4f6f9',
            'surface' => '#ffffff',
            'text' => '#0f172a',
            'text_muted' => '#64748b',
        ],
        'catalogo' => [
            'primary' => '#334155',
            'accent' => '#0ea5e9',
            'background' => '#f8fafc',
            'surface' => '#ffffff',
            'text' => '#1e293b',
            'text_muted' => '#64748b',
        ],
        'otaku' => [
            'primary' => '#ff5500',
            'accent' => '#ffb800',
            'background' => '#0a0a0a',
            'surface' => '#141414',
            'text' => '#ffffff',
            'text_muted' => '#ff9944',
            'font_heading' => 'bebas_neue',
            'font_body' => 'noto_sans_jp',
        ],
        'japo' => [
            'primary' => '#c41e3a',
            'accent' => '#d4af37',
            'background' => '#0f0808',
            'surface' => '#1a1010',
            'text' => '#f5f0eb',
            'text_muted' => '#c4a882',
            'font_heading' => 'noto_sans_jp',
            'font_body' => 'inter',
        ],
        'fastfood' => [
            'primary' => '#d62828',
            'accent' => '#ffbe0b',
            'background' => '#fff5e6',
            'surface' => '#ffffff',
            'text' => '#141414',
            'text_muted' => '#5c4033',
            'font_heading' => 'bebas_neue',
            'font_body' => 'open_sans',
        ],
        'pizza' => [
            'primary' => '#c62828',
            'accent' => '#2e7d32',
            'background' => '#fff8f0',
            'surface' => '#ffffff',
            'text' => '#1b1b1b',
            'text_muted' => '#6d4c41',
            'font_heading' => 'bebas_neue',
            'font_body' => 'open_sans',
        ],
        'mar' => [
            'primary' => '#0277bd',
            'accent' => '#00b4d8',
            'background' => '#e0f7fa',
            'surface' => '#ffffff',
            'text' => '#0d3b5c',
            'text_muted' => '#546e7a',
            'font_heading' => 'lora',
            'font_body' => 'inter',
        ],
        'elegance' => [
            'primary' => '#1a1a2e',
            'accent' => '#c9a962',
            'background' => '#faf8f5',
            'surface' => '#ffffff',
            'text' => '#1a1a2e',
            'text_muted' => '#6b6b7b',
            'font_heading' => 'playfair',
            'font_body' => 'lora',
        ],
        'asador' => [
            'primary' => '#ff5722',
            'accent' => '#ffab40',
            'background' => '#141010',
            'surface' => '#1e1816',
            'text' => '#f5f0eb',
            'text_muted' => '#bcaaa4',
            'font_heading' => 'montserrat',
            'font_body' => 'inter',
        ],
        'saffron' => [
            'primary' => '#c75b3a',
            'accent' => '#6b8f71',
            'background' => '#faf6f1',
            'surface' => '#ffffff',
            'text' => '#2c1810',
            'text_muted' => '#7a6558',
            'font_heading' => 'cormorant',
            'font_body' => 'montserrat',
        ],
        'velvet' => [
            'primary' => '#a63d5c',
            'accent' => '#d4a574',
            'background' => '#0a090c',
            'surface' => '#151219',
            'text' => '#f5f0eb',
            'text_muted' => '#a89ba8',
            'font_heading' => 'cormorant',
            'font_body' => 'inter',
        ],
        'atelier' => [
            'primary' => '#ffffff',
            'accent' => '#ff6b35',
            'background' => '#050505',
            'surface' => '#111114',
            'text' => '#fafafa',
            'text_muted' => '#8a8a92',
            'font_heading' => 'bebas_neue',
            'font_body' => 'montserrat',
        ],
        'maison' => [
            'primary' => '#f5f3ef',
            'accent' => '#c4a574',
            'background' => '#0f0e0d',
            'surface' => '#1a1917',
            'text' => '#f5f3ef',
            'text_muted' => '#8a8478',
            'font_heading' => 'cormorant',
            'font_body' => 'lora',
        ],
    ],

  /*
  | Paletas rápidas por plantilla (nombre => colores)
  */
    'presets' => [
        'lumiere' => [
            'Noche elegante' => [
                'primary' => '#7ec8ff',
                'accent' => '#c9a962',
                'background' => '#0d1117',
                'surface' => '#161b22',
                'text' => '#f0f6fc',
                'text_muted' => '#8b949e',
            ],
            'Carbón y oro' => [
                'primary' => '#e8d5a3',
                'accent' => '#d4af37',
                'background' => '#121212',
                'surface' => '#1e1e1e',
                'text' => '#fafafa',
                'text_muted' => '#9e9e9e',
            ],
            'Medianoche azul' => [
                'primary' => '#64b5f6',
                'accent' => '#ff8a65',
                'background' => '#0a1628',
                'surface' => '#132238',
                'text' => '#eceff1',
                'text_muted' => '#90a4ae',
            ],
        ],
        'bistro' => [
            'Clásico marino' => [
                'primary' => '#1e3a5f',
                'accent' => '#f5c518',
                'background' => '#f0f2f5',
                'surface' => '#ffffff',
                'text' => '#1a2332',
                'text_muted' => '#64748b',
            ],
            'Fresco verde' => [
                'primary' => '#2d6a4f',
                'accent' => '#95d5b2',
                'background' => '#f8faf9',
                'surface' => '#ffffff',
                'text' => '#1b4332',
                'text_muted' => '#52796f',
            ],
            'Terracota' => [
                'primary' => '#9c4221',
                'accent' => '#f4a261',
                'background' => '#faf6f2',
                'surface' => '#ffffff',
                'text' => '#3d2817',
                'text_muted' => '#8b7355',
            ],
        ],
        'basic' => [
            'Webnu azul' => [
                'primary' => '#0074d9',
                'accent' => '#e65100',
                'background' => '#ffffff',
                'surface' => '#f8f9fa',
                'text' => '#212529',
                'text_muted' => '#6c757d',
            ],
        ],
        'pasion' => [
            'Vino tinto' => [
                'primary' => '#8b0000',
                'accent' => '#d4a017',
                'background' => '#fff8f0',
                'surface' => '#ffffff',
                'text' => '#2c1810',
                'text_muted' => '#6b5344',
            ],
        ],
        'oriental' => [
            'Rojo imperial' => [
                'primary' => '#c41e3a',
                'accent' => '#d4af37',
                'background' => '#1a1a1a',
                'surface' => '#2d2d2d',
                'text' => '#f5f5f5',
                'text_muted' => '#a0a0a0',
            ],
        ],
        'visual' => [
            'Azul moderno' => [
                'primary' => '#1565c0',
                'accent' => '#ff6f00',
                'background' => '#fafafa',
                'surface' => '#ffffff',
                'text' => '#212121',
                'text_muted' => '#757575',
            ],
        ],
        'nocturne' => [
            'Coctelería' => [
                'primary' => '#7ec8ff',
                'accent' => '#c9a962',
                'background' => '#0a0e14',
                'surface' => '#141a22',
                'text' => '#f4f7fb',
                'text_muted' => '#9aa8b8',
            ],
        ],
        'temporada' => [
            'Primavera' => [
                'primary' => '#1e3a5f',
                'accent' => '#2563eb',
                'background' => '#f4f6f9',
                'surface' => '#ffffff',
                'text' => '#0f172a',
                'text_muted' => '#64748b',
            ],
        ],
        'catalogo' => [
            'Minimal' => [
                'primary' => '#334155',
                'accent' => '#0ea5e9',
                'background' => '#f8fafc',
                'surface' => '#ffffff',
                'text' => '#1e293b',
                'text_muted' => '#64748b',
            ],
        ],
        'otaku' => [
            'Neón naranja' => [
                'primary' => '#ff5500',
                'accent' => '#ffb800',
                'background' => '#0a0a0a',
                'surface' => '#141414',
                'text' => '#ffffff',
                'text_muted' => '#ff9944',
            ],
        ],
        'japo' => [
            'Lacado imperial' => [
                'primary' => '#c41e3a',
                'accent' => '#d4af37',
                'background' => '#0f0808',
                'surface' => '#1a1010',
                'text' => '#f5f0eb',
                'text_muted' => '#c4a882',
            ],
        ],
        'fastfood' => [
            'Burger clásico' => [
                'primary' => '#e53935',
                'accent' => '#ffc107',
                'background' => '#fff8e7',
                'surface' => '#ffffff',
                'text' => '#1a1a1a',
                'text_muted' => '#5d4037',
            ],
        ],
        'pizza' => [
            'Forno clásico' => [
                'primary' => '#c62828',
                'accent' => '#2e7d32',
                'background' => '#fff8f0',
                'surface' => '#ffffff',
                'text' => '#1b1b1b',
                'text_muted' => '#6d4c41',
            ],
        ],
        'mar' => [
            'Mediterráneo' => [
                'primary' => '#0277bd',
                'accent' => '#00b4d8',
                'background' => '#e0f7fa',
                'surface' => '#ffffff',
                'text' => '#0d3b5c',
                'text_muted' => '#546e7a',
            ],
        ],
        'elegance' => [
            'Ivory & gold' => [
                'primary' => '#1a1a2e',
                'accent' => '#c9a962',
                'background' => '#faf8f5',
                'surface' => '#ffffff',
                'text' => '#1a1a2e',
                'text_muted' => '#6b6b7b',
            ],
        ],
        'asador' => [
            'Brasa viva' => [
                'primary' => '#ff5722',
                'accent' => '#ffab40',
                'background' => '#141010',
                'surface' => '#1e1816',
                'text' => '#f5f0eb',
                'text_muted' => '#bcaaa4',
            ],
        ],
        'saffron' => [
            'Terracota mediterránea' => [
                'primary' => '#c75b3a',
                'accent' => '#6b8f71',
                'background' => '#faf6f1',
                'surface' => '#ffffff',
                'text' => '#2c1810',
                'text_muted' => '#7a6558',
            ],
            'Atardecer costero' => [
                'primary' => '#d4764a',
                'accent' => '#4a7c59',
                'background' => '#fff9f4',
                'surface' => '#ffffff',
                'text' => '#3d2817',
                'text_muted' => '#8b7355',
            ],
        ],
        'velvet' => [
            'Speakeasy' => [
                'primary' => '#a63d5c',
                'accent' => '#d4a574',
                'background' => '#0a090c',
                'surface' => '#151219',
                'text' => '#f5f0eb',
                'text_muted' => '#a89ba8',
            ],
            'Borgoña profundo' => [
                'primary' => '#8b2942',
                'accent' => '#c9a962',
                'background' => '#08070a',
                'surface' => '#121018',
                'text' => '#faf8f6',
                'text_muted' => '#9a8f96',
            ],
        ],
        'atelier' => [
            'Negro y coral' => [
                'primary' => '#ffffff',
                'accent' => '#ff6b35',
                'background' => '#050505',
                'surface' => '#111114',
                'text' => '#fafafa',
                'text_muted' => '#8a8a92',
            ],
            'Medianoche lima' => [
                'primary' => '#f5ffe8',
                'accent' => '#c8f542',
                'background' => '#060608',
                'surface' => '#101012',
                'text' => '#f5f5f7',
                'text_muted' => '#909098',
            ],
        ],
        'maison' => [
            'Espresso y oro' => [
                'primary' => '#f5f3ef',
                'accent' => '#c4a574',
                'background' => '#0f0e0d',
                'surface' => '#1a1917',
                'text' => '#f5f3ef',
                'text_muted' => '#8a8478',
            ],
            'Noche de perla' => [
                'primary' => '#faf9f7',
                'accent' => '#d4b896',
                'background' => '#0a0908',
                'surface' => '#141210',
                'text' => '#faf9f7',
                'text_muted' => '#9a9488',
            ],
        ],
    ],
];
