<?php

return [

    'default' => 'menu',

    'layouts' => ['menu', 'spotlight', 'featured', 'video', 'daily', 'hero', 'tapas'],

    'templates' => [
        'menu' => [
            'key' => 'menu',
            'label' => 'Carta completa',
            'description' => 'Secciones y platos con precios, legible en pantalla grande.',
            'layout' => 'menu',
            'view' => 'tv.templates.menu',
            'duration_hint' => 'Rotación automática de secciones',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-layout-grid',
            'thumbnail' => 'img/tvpik/previews/menu.svg',
        ],
        'spotlight' => [
            'key' => 'spotlight',
            'label' => 'Plato del día',
            'description' => 'Especial de hoy destacado con precio y platos recomendados.',
            'layout' => 'spotlight',
            'view' => 'tv.templates.spotlight',
            'duration_hint' => 'Ideal para entrada o cartelería principal',
            'rotate_seconds' => 0,
            'show_header' => true,
            'icon' => 'ti-star',
            'thumbnail' => 'img/tvpik/previews/spotlight.svg',
        ],
        'featured' => [
            'key' => 'featured',
            'label' => 'Destacados',
            'description' => 'Carrusel de platos marcados como destacados o con foto.',
            'layout' => 'featured',
            'view' => 'tv.templates.featured',
            'duration_hint' => 'Cambio automático cada pocos segundos',
            'rotate_seconds' => 8,
            'show_header' => true,
            'icon' => 'ti-photo',
            'thumbnail' => 'img/tvpik/previews/featured.svg',
        ],
        'video' => [
            'key' => 'video',
            'label' => 'Vídeos de platos',
            'description' => 'Reels y vídeos cortos de productos con vídeo.',
            'layout' => 'video',
            'view' => 'tv.templates.video',
            'duration_hint' => 'Reproduce en bucle los vídeos disponibles',
            'rotate_seconds' => 15,
            'show_header' => false,
            'icon' => 'ti-player-play',
            'thumbnail' => 'img/tvpik/previews/video.svg',
        ],
        'daily' => [
            'key' => 'daily',
            'label' => 'Menú del día',
            'description' => 'Menú fijo con primeros, segundos y postres, precio destacado y foto del plato estrella.',
            'layout' => 'daily',
            'view' => 'tv.templates.daily',
            'duration_hint' => 'Si tienes varios menús, rota entre ellos en la misma pantalla',
            'rotate_seconds' => 15,
            'show_header' => false,
            'icon' => 'ti-bowl-spoon',
            'thumbnail' => 'img/tvpik/previews/daily.svg',
            'supports_menu_selector' => true,
        ],
        'hero' => [
            'key' => 'hero',
            'label' => 'Plato hero',
            'description' => 'Plato destacado a pantalla completa con título grande y categoría.',
            'layout' => 'hero',
            'view' => 'tv.templates.hero',
            'duration_hint' => 'Rota entre los platos destacados con foto',
            'rotate_seconds' => 10,
            'show_header' => false,
            'icon' => 'ti-photo-filled',
            'thumbnail' => 'img/tvpik/previews/hero.svg',
        ],
        'tapas' => [
            'key' => 'tapas',
            'label' => 'Tapas / Destacados',
            'description' => 'Rejilla 2x2 con tus platos estrella y precio destacado.',
            'layout' => 'tapas',
            'view' => 'tv.templates.tapas',
            'duration_hint' => 'Cambio automático de grupos si hay más de 4 destacados',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-grid-dots',
            'thumbnail' => 'img/tvpik/previews/tapas.svg',
        ],
    ],

];
