<?php

return [

    'default' => 'menu',

    'layouts' => [
        'menu', 'spotlight', 'featured', 'video', 'daily', 'hero', 'tapas',
        'menu_video', 'menu_banner',
        'cinema', 'sommelier', 'degustacion', 'signature', 'lounge', 'marquee',
    ],

    /*
    | Categorías / motivos de plantilla TV. Claves usadas en templates[].category.
    | TVPik muestra filtros cuando hay más de una categoría en el catálogo activo.
    | Añade aquí una entrada antes de asignar category en una plantilla nueva.
    */
    'categories' => [
        'restaurant' => [
            'label' => 'Restauración',
        ],
        'retail' => [
            'label' => 'Comercio',
        ],
        'events' => [
            'label' => 'Eventos',
        ],
        'general' => [
            'label' => 'General',
        ],
    ],

    'templates' => [
        'menu' => [
            'key' => 'menu',
            'label' => 'Carta completa',
            'description' => 'Secciones y platos con precios, legible en pantalla grande.',
            'category' => 'restaurant',
            'layout' => 'menu',
            'view' => 'tv.templates.menu',
            'duration_hint' => 'Rotación automática de secciones',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-layout-grid',
            'thumbnail' => 'img/tvpik/previews/menu.svg',
        ],
        'spotlight' => [
            'key' => 'spotlight',
            'label' => 'Plato del día',
            'description' => 'Especial de hoy destacado con precio y platos recomendados.',
            'category' => 'restaurant',
            'layout' => 'spotlight',
            'view' => 'tv.templates.spotlight',
            'duration_hint' => 'Ideal para entrada o cartelería principal',
            'rotate_seconds' => 0,
            'show_header' => true,
            'icon' => 'ti-star',
            'thumbnail' => 'img/tvpik/previews/spotlight.svg',
        ],
        'featured' => [
            'key' => 'featured',
            'label' => 'Destacados',
            'description' => 'Carrusel de platos marcados como destacados o con foto.',
            'category' => 'restaurant',
            'layout' => 'featured',
            'view' => 'tv.templates.featured',
            'duration_hint' => 'Cambio automático cada pocos segundos',
            'rotate_seconds' => 8,
            'show_header' => true,
            'icon' => 'ti-photo',
            'thumbnail' => 'img/tvpik/previews/featured.svg',
        ],
        'video' => [
            'key' => 'video',
            'label' => 'Vídeos de platos',
            'description' => 'Reels y vídeos cortos de productos con vídeo.',
            'category' => 'restaurant',
            'layout' => 'video',
            'view' => 'tv.templates.video',
            'duration_hint' => 'Reproduce en bucle los vídeos disponibles',
            'rotate_seconds' => 15,
            'show_header' => false,
            'icon' => 'ti-player-play',
            'thumbnail' => 'img/tvpik/previews/video.svg',
        ],
        'menu_video' => [
            'key' => 'menu_video',
            'label' => 'Carta + vídeos',
            'description' => 'Carta a la izquierda y carrusel de vídeos de platos a la derecha.',
            'category' => 'restaurant',
            'layout' => 'menu_video',
            'view' => 'tv.templates.menu_video',
            'duration_hint' => 'Menú y reels de platos a la vez',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-layout-sidebar-right',
            'thumbnail' => 'img/tvpik/previews/menu.svg',
        ],
        'menu_banner' => [
            'key' => 'menu_banner',
            'label' => 'Carta con banner vídeo',
            'description' => 'Vídeos de platos arriba y carta completa abajo.',
            'category' => 'restaurant',
            'layout' => 'menu_banner',
            'view' => 'tv.templates.menu_banner',
            'duration_hint' => 'Banner promocional + carta legible',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-layout-rows',
            'thumbnail' => 'img/tvpik/previews/video.svg',
        ],
        'daily' => [
            'key' => 'daily',
            'label' => 'Menú del día',
            'description' => 'Menú fijo con primeros, segundos y postres, precio destacado y foto del plato estrella.',
            'category' => 'restaurant',
            'layout' => 'daily',
            'view' => 'tv.templates.daily',
            'duration_hint' => 'Si tienes varios menús, rota entre ellos en la misma pantalla',
            'rotate_seconds' => 15,
            'show_header' => false,
            'icon' => 'ti-bowl-spoon',
            'thumbnail' => 'img/tvpik/previews/daily.svg',
            'supports_menu_selector' => true,
        ],
        'hero' => [
            'key' => 'hero',
            'label' => 'Plato hero',
            'description' => 'Plato destacado a pantalla completa con título grande y categoría.',
            'category' => 'restaurant',
            'layout' => 'hero',
            'view' => 'tv.templates.hero',
            'duration_hint' => 'Rota entre los platos destacados con foto',
            'rotate_seconds' => 10,
            'show_header' => false,
            'icon' => 'ti-photo-filled',
            'thumbnail' => 'img/tvpik/previews/hero.svg',
        ],
        'tapas' => [
            'key' => 'tapas',
            'label' => 'Tapas / Destacados',
            'description' => 'Rejilla 2x2 con tus platos estrella y precio destacado.',
            'category' => 'restaurant',
            'layout' => 'tapas',
            'view' => 'tv.templates.tapas',
            'duration_hint' => 'Cambio automático de grupos si hay más de 4 destacados',
            'rotate_seconds' => 12,
            'show_header' => true,
            'icon' => 'ti-grid-dots',
            'thumbnail' => 'img/tvpik/previews/tapas.svg',
        ],
        'cinema' => [
            'key' => 'cinema',
            'label' => 'Cinema',
            'description' => 'Plato a pantalla completa con tratamiento cinematográfico y Ken Burns.',
            'category' => 'restaurant',
            'layout' => 'cinema',
            'view' => 'tv.templates.cinema',
            'duration_hint' => 'Carrusel lento entre platos con foto',
            'rotate_seconds' => 14,
            'show_header' => false,
            'icon' => 'ti-movie',
            'thumbnail' => 'img/tvpik/previews/cinema.svg',
            'premium' => true,
        ],
        'sommelier' => [
            'key' => 'sommelier',
            'label' => 'Sommelier',
            'description' => 'Lista elegante por secciones, ideal para vinos y coctelería.',
            'category' => 'restaurant',
            'layout' => 'sommelier',
            'view' => 'tv.templates.sommelier',
            'duration_hint' => 'Rota secciones con transición suave',
            'rotate_seconds' => 18,
            'show_header' => true,
            'icon' => 'ti-glass-full',
            'thumbnail' => 'img/tvpik/previews/sommelier.svg',
            'premium' => true,
        ],
        'degustacion' => [
            'key' => 'degustacion',
            'label' => 'Degustación',
            'description' => 'Menú del día como experiencia narrativa: entrante, principal y postre.',
            'category' => 'restaurant',
            'layout' => 'degustacion',
            'view' => 'tv.templates.degustacion',
            'duration_hint' => 'Rota entre menús si tienes varios activos',
            'rotate_seconds' => 20,
            'show_header' => false,
            'icon' => 'ti-tools-kitchen-2',
            'thumbnail' => 'img/tvpik/previews/degustacion.svg',
            'supports_menu_selector' => true,
            'premium' => true,
        ],
        'signature' => [
            'key' => 'signature',
            'label' => 'Firma del chef',
            'description' => 'Plato estrella con foto, descripción y sello de sugerencia del chef.',
            'category' => 'restaurant',
            'layout' => 'signature',
            'view' => 'tv.templates.signature',
            'duration_hint' => 'Carrusel de platos con historia',
            'rotate_seconds' => 12,
            'show_header' => false,
            'icon' => 'ti-signature',
            'thumbnail' => 'img/tvpik/previews/signature.svg',
            'premium' => true,
        ],
        'lounge' => [
            'key' => 'lounge',
            'label' => 'Lounge',
            'description' => 'Ambiente del local y recomendaciones cortas para bar o hotel.',
            'category' => 'restaurant',
            'layout' => 'lounge',
            'view' => 'tv.templates.lounge',
            'duration_hint' => 'Fondo rotativo con lista fija de recomendaciones',
            'rotate_seconds' => 10,
            'show_header' => true,
            'icon' => 'ti-armchair',
            'thumbnail' => 'img/tvpik/previews/lounge.svg',
            'premium' => true,
        ],
        'marquee' => [
            'key' => 'marquee',
            'label' => 'Marquee',
            'description' => 'Hero rotativo arriba y ticker continuo de platos abajo.',
            'category' => 'restaurant',
            'layout' => 'marquee',
            'view' => 'tv.templates.marquee',
            'duration_hint' => 'Ideal para barra y locales con mucho movimiento',
            'rotate_seconds' => 8,
            'show_header' => false,
            'icon' => 'ti-layout-rows',
            'thumbnail' => 'img/tvpik/previews/marquee.svg',
            'premium' => true,
        ],
    ],

];
